/* $Id: nblast.cpp,v 1.1.1.1 2003/02/07 09:32:34 root Exp $
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 * Author:  .......
 *
 * File Description:
 *   .......
 *
 * Remark:
 *   This code was originally generated by application DATATOOL
 *   using specifications from the data definition file
 *   'NBlastasn.asn'.
 */

// standard includes

// generated includes
#include <nblast.hpp>

// generated classes

BEGIN_seqhound_SCOPE // namespace seqhound::

// destructor
CNBlast_Result_Set::~CNBlast_Result_Set(void)
{
}

// destructor
CNBlast_Scores::~CNBlast_Scores(void)
{
}

// destructor
CNBlast_Result::~CNBlast_Result(void)
{
}

// destructor
CNBlast_GiAndEval_set::~CNBlast_GiAndEval_set(void)
{
}

// destructor
CNBlast_GiAndEval::~CNBlast_GiAndEval(void)
{
}

END_seqhound_SCOPE // namespace seqhound::


/*
* ===========================================================================
*
* $Log: nblast.cpp,v $
* Revision 1.1.1.1  2003/02/07 09:32:34  root
* Automated import from Sourceforge.net
*
* Revision 1.1  2003/02/06 15:10:43  haocl
* new nblast and slristruc files, and modifications to existing files
*
*
* ===========================================================================
*/
/* Original file checksum: lines: 80, chars: 2072, CRC32: 4e976e3e */
