/* $Id: shproteinreport.cpp,v 1.2 2003/09/29 22:17:49 haocl Exp $
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 * Author:  .......
 *
 * File Description:
 *   .......
 *
 * Remark:
 *   This code was originally generated by application DATATOOL
 *   using specifications from the data definition file
 *   'slristruc.asn'.
 */

// standard includes

// generated includes
#include <shproteinreport.hpp>

// generated classes

BEGIN_shoundcgi_SCOPE // namespace shoundcgi::

// destructor
CSHProteinReportSetDescription::~CSHProteinReportSetDescription(void)
{
}

// destructor
CSHProteinReportSet::~CSHProteinReportSet(void)
{
}

// destructor
CSHProteinReport::~CSHProteinReport(void)
{
}

// destructor
CSHNeighbour::~CSHNeighbour(void)
{
}

// destructor
CSHLocusProduct::~CSHLocusProduct(void)
{
}

// destructor
CSHLocusLinkReport::~CSHLocusLinkReport(void)
{
}

// destructor
CSHGoReport::~CSHGoReport(void)
{
}

// destructor
CSHGoAnnotNode::~CSHGoAnnotNode(void)
{
}

// destructor
CSHGoAnnot::~CSHGoAnnot(void)
{
}

END_shoundcgi_SCOPE // namespace shoundcgi::


/*
* ===========================================================================
*
* $Log: shproteinreport.cpp,v $
* Revision 1.2  2003/09/29 22:17:49  haocl
* checkin after newly generated
*
*
* ===========================================================================
*/
/* Original file checksum: lines: 100, chars: 2303, CRC32: 521b071c */
