/* $Id: slristruc.cpp,v 1.2 2003/09/29 22:17:49 haocl Exp $
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 * Author:  .......
 *
 * File Description:
 *   .......
 *
 * Remark:
 *   This code was originally generated by application DATATOOL
 *   using specifications from the data definition file
 *   'slristruc.asn'.
 */

// standard includes

// generated includes
#include <slristruc.hpp>

// generated classes

BEGIN_seqhound_SCOPE // namespace seqhound::

// destructor
CStTaxgiNode::~CStTaxgiNode(void)
{
}

// destructor
CStTaxgi::~CStTaxgi(void)
{
}

// destructor
CStSengiNode::~CStSengiNode(void)
{
}

// destructor
CStSengi::~CStSengi(void)
{
}

// destructor
CStSendbNode::~CStSendbNode(void)
{
}

// destructor
CStSendb::~CStSendb(void)
{
}

// destructor
CStRpsdb::~CStRpsdb(void)
{
}

// destructor
CStRpsNode::~CStRpsNode(void)
{
}

// destructor
CStRedundNode::~CStRedundNode(void)
{
}

// destructor
CStRedund::~CStRedund(void)
{
}

// destructor
CStPubseqNode::~CStPubseqNode(void)
{
}

// destructor
CStPubseq::~CStPubseq(void)
{
}

// destructor
CStPartiNode::~CStPartiNode(void)
{
}

// destructor
CStParti::~CStParti(void)
{
}

// destructor
CStOMIMdbNode::~CStOMIMdbNode(void)
{
}

// destructor
CStOMIMdb::~CStOMIMdb(void)
{
}

// destructor
CStNucprotNode::~CStNucprotNode(void)
{
}

// destructor
CStNucprot::~CStNucprot(void)
{
}

// destructor
CStMmgiNode::~CStMmgiNode(void)
{
}

// destructor
CStMmgi::~CStMmgi(void)
{
}

// destructor
CStMmdbNode::~CStMmdbNode(void)
{
}

// destructor
CStMmdb::~CStMmdb(void)
{
}

// destructor
CStLLdbNode::~CStLLdbNode(void)
{
}

// destructor
CStLLdb::~CStLLdb(void)
{
}

// destructor
CStHistdbNode::~CStHistdbNode(void)
{
}

// destructor
CStHistdb::~CStHistdb(void)
{
}

// destructor
CStGOdbNode::~CStGOdbNode(void)
{
}

// destructor
CStGOdb::~CStGOdb(void)
{
}

// destructor
CStDomdbNode::~CStDomdbNode(void)
{
}

// destructor
CStDomdb::~CStDomdb(void)
{
}

// destructor
CStDomNamedb::~CStDomNamedb(void)
{
}

// destructor
CStDomNameNode::~CStDomNameNode(void)
{
}

// destructor
CStChromNode::~CStChromNode(void)
{
}

// destructor
CStChrom::~CStChrom(void)
{
}

// destructor
CStCddbNode::~CStCddbNode(void)
{
}

// destructor
CStCddb::~CStCddb(void)
{
}

// destructor
CStCDDdbNode::~CStCDDdbNode(void)
{
}

// destructor
CStCDDdb::~CStCDDdb(void)
{
}

// destructor
CStAsndbNode::~CStAsndbNode(void)
{
}

// destructor
CStAsndb::~CStAsndb(void)
{
}

// destructor
CStAccdbNode::~CStAccdbNode(void)
{
}

// destructor
CStAccdb::~CStAccdb(void)
{
}

END_seqhound_SCOPE // namespace seqhound::


/*
* ===========================================================================
*
* $Log: slristruc.cpp,v $
* Revision 1.2  2003/09/29 22:17:49  haocl
* checkin after newly generated
*
*
* ===========================================================================
*/
/* Original file checksum: lines: 265, chars: 3647, CRC32: 11acf7cb */
