/* $Id: objslrilinkset.cpp,v 1.2 2003/09/30 18:06:17 haocl Exp $
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 * Author:  .......
 *
 * File Description:
 *   .......
 *
 * Remark:
 *   This code was originally generated by application DATATOOL
 *   using specifications from the data definition file
 *   'slrilinkset.asn'.
 */

// standard includes

// generated includes
#include <objslrilinkset.hpp>

// generated classes

BEGIN_slri_SCOPE // namespace slri::

// destructor
CYLink_set_List3::~CYLink_set_List3(void)
{
}

// destructor
CYLink_set_List2::~CYLink_set_List2(void)
{
}

// destructor
CYLink_set_List::~CYLink_set_List(void)
{
}

// destructor
CYLink_set::~CYLink_set(void)
{
}

// destructor
CLLink_set_List3::~CLLink_set_List3(void)
{
}

// destructor
CLLink_set_List2::~CLLink_set_List2(void)
{
}

// destructor
CLLink_set_List::~CLLink_set_List(void)
{
}

// destructor
CLLink_set::~CLLink_set(void)
{
}

// destructor
CIVectorList::~CIVectorList(void)
{
}

// destructor
CIVector::~CIVector(void)
{
}

// destructor
CIMatrixListSet::~CIMatrixListSet(void)
{
}

// destructor
CIMatrixList::~CIMatrixList(void)
{
}

// destructor
CIMatrix::~CIMatrix(void)
{
}

// destructor
CILink_set_List3::~CILink_set_List3(void)
{
}

// destructor
CILink_set_List2::~CILink_set_List2(void)
{
}

// destructor
CILink_set_List::~CILink_set_List(void)
{
}

// destructor
CILink_set::~CILink_set(void)
{
}

// destructor
CFLink_set_List3::~CFLink_set_List3(void)
{
}

// destructor
CFLink_set_List2::~CFLink_set_List2(void)
{
}

// destructor
CFLink_set_List::~CFLink_set_List(void)
{
}

// destructor
CFLink_set::~CFLink_set(void)
{
}

// destructor
CCLink_set_List3::~CCLink_set_List3(void)
{
}

// destructor
CCLink_set_List2::~CCLink_set_List2(void)
{
}

// destructor
CCLink_set_List::~CCLink_set_List(void)
{
}

// destructor
CCLink_set::~CCLink_set(void)
{
}

// destructor
CBLink_set_List3::~CBLink_set_List3(void)
{
}

// destructor
CBLink_set_List2::~CBLink_set_List2(void)
{
}

// destructor
CBLink_set_List::~CBLink_set_List(void)
{
}

// destructor
CBLink_set::~CBLink_set(void)
{
}

END_slri_SCOPE // namespace slri::


/*
* ===========================================================================
*
* $Log: objslrilinkset.cpp,v $
* Revision 1.2  2003/09/30 18:06:17  haocl
* merged DNode, DTree, DKey, DData into slrilibstruc,
* merged IVector*, IMatrix* into slrilinkset
*
*
* ===========================================================================
*/
/* Original file checksum: lines: 200, chars: 3268, CRC32: 91c520a7 */
