package dbxrefService;

# -- generated by SOAP::Lite (v0.60) for Perl -- soaplite.com -- Copyright (C) 2000-2001 Paul Kulchenko --
# -- generated from http://seqhound.blueprint.org:8080/soap/dbxref.wsdl.xml [Fri Apr 22 14:21:32 2005]

my %methods = (
  SHoundGetDxCvTermList => {
    endpoint => 'http://seqhound.blueprint.org:8080/soap/services/dbxref',
    soapaction => 'urn:dbxref#SHoundGetDxCvTermList',
    uri => 'urn:dbxref',
    parameters => [
    ],
  },
  SHoundDxListFromSource => {
    endpoint => 'http://seqhound.blueprint.org:8080/soap/services/dbxref',
    soapaction => 'urn:dbxref#SHoundDxListFromSource',
    uri => 'urn:dbxref',
    parameters => [
      SOAP::Data->new(name => 'dbName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'recordId', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'field', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'cv', type => 'xsd:integer', attr => {}),
    ],
  },
  SHoundGetDxDbnames => {
    endpoint => 'http://seqhound.blueprint.org:8080/soap/services/dbxref',
    soapaction => 'urn:dbxref#SHoundGetDxDbnames',
    uri => 'urn:dbxref',
    parameters => [
      SOAP::Data->new(name => 'source_dxnames', type => 'xsd:boolean', attr => {}),
      SOAP::Data->new(name => 'dxnames', type => 'xsd:boolean', attr => {}),
    ],
  },
  SHoundDxFieldNameListFromDbName => {
    endpoint => 'http://seqhound.blueprint.org:8080/soap/services/dbxref',
    soapaction => 'urn:dbxref#SHoundDxFieldNameListFromDbName',
    uri => 'urn:dbxref',
    parameters => [
      SOAP::Data->new(name => 'dbName', type => 'xsd:string', attr => {}),
    ],
  },
  SHoundSourceListFromDx => {
    endpoint => 'http://seqhound.blueprint.org:8080/soap/services/dbxref',
    soapaction => 'urn:dbxref#SHoundSourceListFromDx',
    uri => 'urn:dbxref',
    parameters => [
      SOAP::Data->new(name => 'dbName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'recordId', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'field', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'cv', type => 'xsd:integer', attr => {}),
    ],
  },
  SHoundDxListFromGi => {
    endpoint => 'http://seqhound.blueprint.org:8080/soap/services/dbxref',
    soapaction => 'urn:dbxref#SHoundDxListFromGi',
    uri => 'urn:dbxref',
    parameters => [
      SOAP::Data->new(name => 'gi', type => 'xsd:int', attr => {}),
    ],
  },
);

use SOAP::Lite;
use Exporter;
use Carp ();

use vars qw(@ISA $AUTOLOAD @EXPORT_OK %EXPORT_TAGS);
@ISA = qw(Exporter SOAP::Lite);
@EXPORT_OK = (keys %methods);
%EXPORT_TAGS = ('all' => [@EXPORT_OK]);

no strict 'refs';
for my $method (@EXPORT_OK) {
  my %method = %{$methods{$method}};
  *$method = sub {
    my $self = UNIVERSAL::isa($_[0] => __PACKAGE__) 
      ? ref $_[0] ? shift # OBJECT
                  # CLASS, either get self or create new and assign to self
                  : (shift->self || __PACKAGE__->self(__PACKAGE__->new))
      # function call, either get self or create new and assign to self
      : (__PACKAGE__->self || __PACKAGE__->self(__PACKAGE__->new));
    $self->proxy($method{endpoint} || Carp::croak "No server address (proxy) specified") unless $self->proxy;
    my @templates = @{$method{parameters}};
    my $som = $self
      -> endpoint($method{endpoint})
      -> uri($method{uri})
      -> on_action(sub{qq!"$method{soapaction}"!})
      -> call($method => map {@templates ? shift(@templates)->value($_) : $_} @_); 
    UNIVERSAL::isa($som => 'SOAP::SOM') ? wantarray ? $som->paramsall : $som->result 
                                        : $som;
  }
}

sub AUTOLOAD {
  my $method = substr($AUTOLOAD, rindex($AUTOLOAD, '::') + 2);
  return if $method eq 'DESTROY';

  die "Unrecognized method '$method'. List of available method(s): @EXPORT_OK\n";
}

1;
